/**
 * Plain, EN-only internal-operator copy — deliberately NOT `next-intl`
 * (Phase 11's locked contract: `/admin` is EN-only, and admin copy must not
 * expand the customer EN/TH parity burden with operator-only strings).
 */
export const adminCopy = {
  shell: {
    brand: 'Trading OS',
    badge: 'Admin',
    backToApp: 'Back to app',
    signOut: 'Sign out',
    nav: {
      overview: 'Overview',
      users: 'Users',
      workspaces: 'Workspaces',
      audit: 'Audit',
    },
  },
  overview: {
    title: 'Platform Overview',
    generatedAtPrefix: 'Data as of',
    totals: {
      users: 'Total users',
      workspaces: 'Total workspaces',
      usersHint: 'Canonical user records',
      workspacesHint: 'Canonical workspace records',
    },
    subscriptions: {
      sectionTitle: 'Subscriptions',
      statusTitle: 'Subscription status',
      statusCaption:
        'Effective subscription state, resolved the same way every workspace access check resolves it — not the raw stored status.',
      planTitle: 'Plan distribution',
      planCaption:
        'Workspaces by effective plan. Includes complimentary grants — see the source breakdown for which plans were actually paid for.',
      sourceTitle: 'Entitlement source',
      sourceCaption:
        'How each workspace reached its current plan. Complimentary access is never counted as revenue.',
      statusColumn: 'Status',
      planColumn: 'Plan',
      sourceColumn: 'Source',
      countColumn: 'Count',
      statusLabels: {
        trialing: 'Trialing',
        active: 'Active',
        expired: 'Expired',
        canceled: 'Canceled',
      },
      planLabels: {
        starter: 'Starter',
        trader: 'Trader',
        professional: 'Professional',
        none: 'No plan (trial)',
      },
      sourceLabels: {
        trial: 'Trial',
        paid: 'Paid',
        complimentary: 'Complimentary',
      },
    },
    activity: {
      sectionTitle: 'Activity',
      windowLabel: 'Last 30 days · UTC',
      newUsersTitle: 'New users',
      newUsersCaption: 'Users created per UTC calendar day, including days with zero signups.',
      newUsersDescription: 'Daily new user registrations for the last 30 UTC calendar days.',
      tradesTitle: 'Trades logged',
      tradesCaption:
        'Trade records created per UTC calendar day, including soft-deleted trades — this counts journal activity, not current holdings.',
      tradesDescription: 'Daily Trade records created for the last 30 UTC calendar days.',
      dateColumn: 'Date (UTC)',
      countColumn: 'Count',
    },
  },
  /** Shared closed-set labels reused by Users/Workspaces (Phase 11D) — a small deliberate duplicate of `overview.subscriptions.*Labels` (Phase 11C), kept separate so this file never needs to touch the already-verified Overview copy tree. */
  subscriptionLabels: {
    status: {
      trialing: 'Trialing',
      active: 'Active',
      expired: 'Expired',
      canceled: 'Canceled',
    },
    plan: {
      starter: 'Starter',
      trader: 'Trader',
      professional: 'Professional',
      none: 'No plan',
    },
    source: {
      trial: 'Trial',
      paid: 'Paid',
      complimentary: 'Complimentary',
    },
    unknown: 'Unknown',
  },
  providerLabels: {
    email_password: 'Email & password',
    google: 'Google',
    other: 'Other',
  },
  users: {
    title: 'Users',
    description:
      'Canonical user records for support lookups. Read-only — no session, credential, or Trade content is shown here.',
    searchLabel: 'Search by name, email, or user ID',
    searchPlaceholder: 'Search users…',
    searchButton: 'Search',
    clearSearch: 'Clear search',
    columns: {
      name: 'Name',
      email: 'Email',
      verified: 'Verified',
      created: 'Created (UTC)',
      workspaces: 'Workspaces',
    },
    verifiedYes: 'Verified',
    verifiedNo: 'Unverified',
    workspaceNone: 'No workspace',
    emptyTitle: 'No users found',
    emptyDescription: 'No user matches this search. Try a different name, email, or user ID.',
    pagination: { label: 'Users pagination', previous: 'Previous', next: 'Next' },
    loadingLabel: 'Loading users…',
    detail: {
      backToList: 'Back to Users',
      identityTitle: 'Identity',
      nameLabel: 'Name',
      emailLabel: 'Email',
      verifiedLabel: 'Email verified',
      createdLabel: 'Created',
      signInMethodsLabel: 'Sign-in methods',
      noSignInMethods: 'No sign-in method on record',
      workspacesTitle: 'Workspace memberships',
      workspacesEmptyTitle: 'No workspace memberships',
      workspacesEmptyDescription: 'This user is not an active member of any workspace.',
      columns: {
        workspace: 'Workspace',
        role: 'Role',
        status: 'Status',
        plan: 'Plan',
        source: 'Source',
        created: 'Created (UTC)',
      },
      roleOwner: 'Owner',
      roleMember: 'Member',
      loadingLabel: 'Loading user…',
    },
  },
  workspaces: {
    title: 'Workspaces',
    description:
      'Canonical workspace records for support lookups. Read-only — no Strategy, Trade, or billing-provider content is shown here.',
    searchLabel: 'Search by name or workspace ID',
    searchPlaceholder: 'Search workspaces…',
    searchButton: 'Search',
    planFilterLabel: 'Plan',
    sourceFilterLabel: 'Source',
    allPlans: 'All plans',
    allSources: 'All sources',
    resetFilters: 'Reset',
    columns: {
      name: 'Workspace',
      owner: 'Owner',
      status: 'Status',
      plan: 'Plan',
      accounts: 'Trading accounts',
      created: 'Created (UTC)',
    },
    ownerNone: 'No owner on record',
    emptyTitle: 'No workspaces found',
    emptyDescription: 'No workspace matches this search or filter. Try different criteria.',
    pagination: { label: 'Workspaces pagination', previous: 'Previous', next: 'Next' },
    loadingLabel: 'Loading workspaces…',
    detail: {
      backToList: 'Back to Workspaces',
      identityTitle: 'Identity',
      nameLabel: 'Name',
      kindLabel: 'Kind',
      createdLabel: 'Created',
      ownerTitle: 'Owner',
      usageTitle: 'Usage',
      accountsLabel: 'Trading accounts',
      accountsActive: 'active',
      accountsArchived: 'archived',
      strategiesLabel: 'Strategies',
      strategiesArchived: 'archived',
      tradesLabel: 'Trades logged',
      tradesSoftDeleted: 'deleted',
      subscriptionTitle: 'Subscription',
      statusLabel: 'Effective status',
      planLabel: 'Plan',
      sourceLabel: 'Source',
      trialEndsLabel: 'Trial ends',
      periodEndsLabel: 'Current period ends',
      cancelAtPeriodEndLabel: 'Cancels at period end',
      subscriptionSupport: {
        title: 'Subscription Support',
        paidNotice:
          'This Workspace has a paid subscription. Paid lifecycle changes are managed through the canonical customer/payment flow — no Admin mutation is available here.',
        unavailableNotice:
          'This Workspace has no readable entitlement record, so no Support action is available.',
        extendTrial: {
          triggerLabel: 'Extend Trial',
          dialogTitle: 'Extend trial',
          dialogDescription: 'This changes trial access without creating a payment.',
          currentEndLabel: 'Current trial end (UTC)',
          newEndLabel: 'New trial end (UTC)',
          reasonLabel: 'Reason',
          noteLabel: 'Note (optional)',
          reasonOptions: {
            trial_extension_goodwill: 'Goodwill extension',
            support_adjustment: 'Support adjustment',
            other: 'Other',
          },
          submitLabel: 'Extend trial',
          submittingLabel: 'Extending…',
          successLabel: 'Trial extended.',
          noopLabel: 'Trial end unchanged — no action was needed.',
        },
        grantComplimentary: {
          triggerLabel: 'Grant Complimentary Plan',
          changeTriggerLabel: 'Change Complimentary Plan',
          dialogTitle: 'Grant complimentary plan',
          dialogDescription:
            'No payment will be recorded. The selected plan controls the account allowance. Access has no automatic expiry in this MVP. This cannot replace or hide a paid subscription.',
          planLabel: 'Plan',
          reasonLabel: 'Reason',
          noteLabel: 'Note (optional)',
          reasonOptions: {
            complimentary_access: 'Complimentary access',
            support_adjustment: 'Support adjustment',
            other: 'Other',
          },
          confirmLabel: 'Type COMPLIMENTARY to confirm',
          confirmPhrase: 'COMPLIMENTARY',
          submitLabel: 'Grant complimentary plan',
          submittingLabel: 'Granting…',
          successLabel: 'Complimentary plan granted.',
          noopLabel: 'This Workspace already has that complimentary plan — no action was needed.',
        },
        revokeComplimentary: {
          triggerLabel: 'Revoke Complimentary',
          dialogTitle: 'Revoke complimentary access',
          dialogDescription:
            'Complimentary access ends and the Workspace returns to its original trial baseline. If that original trial has already expired, the Workspace becomes effectively read-only. No data is deleted.',
          reasonLabel: 'Reason',
          noteLabel: 'Note (optional)',
          reasonOptions: {
            access_revoke: 'Access revoked',
            support_adjustment: 'Support adjustment',
            other: 'Other',
          },
          confirmLabel: 'Type REVOKE to confirm',
          confirmPhrase: 'REVOKE',
          submitLabel: 'Revoke complimentary access',
          submittingLabel: 'Revoking…',
          successLabel: 'Complimentary access revoked.',
          noopLabel: 'This Workspace was not complimentary — no action was needed.',
        },
        cancelLabel: 'Cancel',
        errors: {
          validation: 'Check the form and try again.',
          unauthenticated: 'Your session has expired. Sign in again.',
          admin_required: 'Platform admin authority is required.',
          not_found: 'This Workspace could not be found.',
          incompatible_state: 'This action is not available for the current subscription state.',
          invalid_transition: 'That change is not a valid transition from the current state.',
          data_integrity_error: 'This record is missing data required for a safe change.',
          unexpected: 'Something went wrong. This has been logged.',
        },
      },
      billingTitle: 'Billing',
      billingNoTransactions: 'No billing transactions on record.',
      billingTransactionCountSuffix: 'total transactions',
      billingLatestLabel: 'Latest transaction',
      billingPlanLabel: 'Plan',
      billingIntervalLabel: 'Interval',
      billingSubtotalLabel: 'Subtotal',
      billingVatLabel: 'VAT',
      billingTotalLabel: 'Total',
      billingStatusLabel: 'Status',
      billingCreatedLabel: 'Created',
      loadingLabel: 'Loading workspace…',
    },
  },
  audit: {
    title: 'Audit',
    description:
      'A read-only, append-only record of platform-admin activity. Every Subscription Support action is recorded here with its reason and structural before/after state.',
    filters: {
      actionLabel: 'Action',
      reasonLabel: 'Reason',
      actorLabel: 'Actor (user ID)',
      subjectUserLabel: 'Subject user ID',
      subjectWorkspaceLabel: 'Subject workspace ID',
      dateLabel: 'Date range',
      allActions: 'All actions',
      allReasons: 'All reasons',
      date30d: 'Last 30 days',
      dateAll: 'All time',
      resetFilters: 'Reset',
      applyLabel: 'Apply',
    },
    actionLabels: {
      'platform_admin.granted': 'Platform admin granted',
      'platform_admin.revoked': 'Platform admin revoked',
      'subscription.trial_extended': 'Trial extended',
      'subscription.complimentary_granted': 'Complimentary plan granted',
      'subscription.complimentary_revoked': 'Complimentary plan revoked',
      'vat.configuration_changed': 'VAT configuration changed',
    },
    reasonLabels: {
      bootstrap: 'Bootstrap',
      access_grant: 'Access granted',
      access_revoke: 'Access revoked',
      trial_extension_goodwill: 'Goodwill extension',
      complimentary_access: 'Complimentary access',
      support_adjustment: 'Support adjustment',
      configuration_change: 'Configuration change',
      other: 'Other',
    },
    columns: {
      timestamp: 'Timestamp (UTC)',
      action: 'Action',
      actor: 'Actor',
      reason: 'Reason',
      subject: 'Subject',
    },
    systemActor: 'System',
    subjectUser: 'User',
    subjectWorkspace: 'Workspace',
    noSubject: '—',
    noteLabel: 'Note',
    beforeLabel: 'Before',
    afterLabel: 'After',
    emptyTitle: 'No audit events found',
    emptyDescription: 'No admin activity matches this filter.',
    pagination: { label: 'Audit pagination', previous: 'Previous', next: 'Next' },
    loadingLabel: 'Loading audit log…',
  },
  errors: {
    title: 'Something went wrong',
    description: 'The operator dashboard could not load its data. This has been logged.',
    retry: 'Try again',
    reference: 'Reference',
  },
  loading: {
    label: 'Loading platform overview…',
  },
  notFound: {
    title: 'Not found',
    description: "This page doesn't exist, or you don't have access to it.",
    backHome: 'Go to sign in',
  },
} as const;
