/**
 * Plain, EN-only internal-operator copy — deliberately NOT `next-intl`
 * (Phase 11's locked contract: `/admin` is EN-only, and admin copy must not
 * expand the customer EN/TH parity burden with operator-only strings).
 */
export const adminCopy = {
  shell: {
    brand: 'Trading OS',
    badge: 'Admin',
    backToApp: 'Back to app',
    signOut: 'Sign out',
    nav: {
      overview: 'Overview',
      users: 'Users',
      workspaces: 'Workspaces',
    },
  },
  overview: {
    title: 'Platform Overview',
    generatedAtPrefix: 'Data as of',
    totals: {
      users: 'Total users',
      workspaces: 'Total workspaces',
      usersHint: 'Canonical user records',
      workspacesHint: 'Canonical workspace records',
    },
    subscriptions: {
      sectionTitle: 'Subscriptions',
      statusTitle: 'Subscription status',
      statusCaption:
        'Effective subscription state, resolved the same way every workspace access check resolves it — not the raw stored status.',
      planTitle: 'Plan distribution',
      planCaption:
        'Workspaces by effective plan. Includes complimentary grants — see the source breakdown for which plans were actually paid for.',
      sourceTitle: 'Entitlement source',
      sourceCaption:
        'How each workspace reached its current plan. Complimentary access is never counted as revenue.',
      statusColumn: 'Status',
      planColumn: 'Plan',
      sourceColumn: 'Source',
      countColumn: 'Count',
      statusLabels: {
        trialing: 'Trialing',
        active: 'Active',
        expired: 'Expired',
        canceled: 'Canceled',
      },
      planLabels: {
        starter: 'Starter',
        trader: 'Trader',
        professional: 'Professional',
        none: 'No plan (trial)',
      },
      sourceLabels: {
        trial: 'Trial',
        paid: 'Paid',
        complimentary: 'Complimentary',
      },
    },
    activity: {
      sectionTitle: 'Activity',
      windowLabel: 'Last 30 days · UTC',
      newUsersTitle: 'New users',
      newUsersCaption: 'Users created per UTC calendar day, including days with zero signups.',
      newUsersDescription: 'Daily new user registrations for the last 30 UTC calendar days.',
      tradesTitle: 'Trades logged',
      tradesCaption:
        'Trade records created per UTC calendar day, including soft-deleted trades — this counts journal activity, not current holdings.',
      tradesDescription: 'Daily Trade records created for the last 30 UTC calendar days.',
      dateColumn: 'Date (UTC)',
      countColumn: 'Count',
    },
  },
  /** Shared closed-set labels reused by Users/Workspaces (Phase 11D) — a small deliberate duplicate of `overview.subscriptions.*Labels` (Phase 11C), kept separate so this file never needs to touch the already-verified Overview copy tree. */
  subscriptionLabels: {
    status: {
      trialing: 'Trialing',
      active: 'Active',
      expired: 'Expired',
      canceled: 'Canceled',
    },
    plan: {
      starter: 'Starter',
      trader: 'Trader',
      professional: 'Professional',
      none: 'No plan',
    },
    source: {
      trial: 'Trial',
      paid: 'Paid',
      complimentary: 'Complimentary',
    },
    unknown: 'Unknown',
  },
  providerLabels: {
    email_password: 'Email & password',
    google: 'Google',
    other: 'Other',
  },
  users: {
    title: 'Users',
    description:
      'Canonical user records for support lookups. Read-only — no session, credential, or Trade content is shown here.',
    searchLabel: 'Search by name, email, or user ID',
    searchPlaceholder: 'Search users…',
    searchButton: 'Search',
    clearSearch: 'Clear search',
    columns: {
      name: 'Name',
      email: 'Email',
      verified: 'Verified',
      created: 'Created (UTC)',
      workspaces: 'Workspaces',
    },
    verifiedYes: 'Verified',
    verifiedNo: 'Unverified',
    workspaceNone: 'No workspace',
    emptyTitle: 'No users found',
    emptyDescription: 'No user matches this search. Try a different name, email, or user ID.',
    pagination: { label: 'Users pagination', previous: 'Previous', next: 'Next' },
    loadingLabel: 'Loading users…',
    detail: {
      backToList: 'Back to Users',
      identityTitle: 'Identity',
      nameLabel: 'Name',
      emailLabel: 'Email',
      verifiedLabel: 'Email verified',
      createdLabel: 'Created',
      signInMethodsLabel: 'Sign-in methods',
      noSignInMethods: 'No sign-in method on record',
      workspacesTitle: 'Workspace memberships',
      workspacesEmptyTitle: 'No workspace memberships',
      workspacesEmptyDescription: 'This user is not an active member of any workspace.',
      columns: {
        workspace: 'Workspace',
        role: 'Role',
        status: 'Status',
        plan: 'Plan',
        source: 'Source',
        created: 'Created (UTC)',
      },
      roleOwner: 'Owner',
      roleMember: 'Member',
      loadingLabel: 'Loading user…',
    },
  },
  workspaces: {
    title: 'Workspaces',
    description:
      'Canonical workspace records for support lookups. Read-only — no Strategy, Trade, or billing-provider content is shown here.',
    searchLabel: 'Search by name or workspace ID',
    searchPlaceholder: 'Search workspaces…',
    searchButton: 'Search',
    planFilterLabel: 'Plan',
    sourceFilterLabel: 'Source',
    allPlans: 'All plans',
    allSources: 'All sources',
    resetFilters: 'Reset',
    columns: {
      name: 'Workspace',
      owner: 'Owner',
      status: 'Status',
      plan: 'Plan',
      accounts: 'Trading accounts',
      created: 'Created (UTC)',
    },
    ownerNone: 'No owner on record',
    emptyTitle: 'No workspaces found',
    emptyDescription: 'No workspace matches this search or filter. Try different criteria.',
    pagination: { label: 'Workspaces pagination', previous: 'Previous', next: 'Next' },
    loadingLabel: 'Loading workspaces…',
    detail: {
      backToList: 'Back to Workspaces',
      identityTitle: 'Identity',
      nameLabel: 'Name',
      kindLabel: 'Kind',
      createdLabel: 'Created',
      ownerTitle: 'Owner',
      usageTitle: 'Usage',
      accountsLabel: 'Trading accounts',
      accountsActive: 'active',
      accountsArchived: 'archived',
      strategiesLabel: 'Strategies',
      strategiesArchived: 'archived',
      tradesLabel: 'Trades logged',
      tradesSoftDeleted: 'deleted',
      subscriptionTitle: 'Subscription',
      statusLabel: 'Effective status',
      planLabel: 'Plan',
      sourceLabel: 'Source',
      trialEndsLabel: 'Trial ends',
      periodEndsLabel: 'Current period ends',
      cancelAtPeriodEndLabel: 'Cancels at period end',
      billingTitle: 'Billing',
      billingNoTransactions: 'No billing transactions on record.',
      billingTransactionCountSuffix: 'total transactions',
      billingLatestLabel: 'Latest transaction',
      billingPlanLabel: 'Plan',
      billingIntervalLabel: 'Interval',
      billingSubtotalLabel: 'Subtotal',
      billingVatLabel: 'VAT',
      billingTotalLabel: 'Total',
      billingStatusLabel: 'Status',
      billingCreatedLabel: 'Created',
      loadingLabel: 'Loading workspace…',
    },
  },
  errors: {
    title: 'Something went wrong',
    description: 'The operator dashboard could not load its data. This has been logged.',
    retry: 'Try again',
    reference: 'Reference',
  },
  loading: {
    label: 'Loading platform overview…',
  },
  notFound: {
    title: 'Not found',
    description: "This page doesn't exist, or you don't have access to it.",
    backHome: 'Go to sign in',
  },
} as const;
